"""
plot_response.py — Step Response Plotter for HiL Flight Controller

Loads the CSV log generated by tb_flight_controller.py and plots
the step response for all three axes (roll, pitch, yaw) in a single
figure with 3 subplots.

Usage:
    python plot_response.py [--csv PATH] [--output PATH]

Default CSV path: hil_flight_log.csv
Default output:   step_response.png
"""

import argparse
import csv
import sys
import os

import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for headless environments
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np


def load_csv(filepath):
    """Load the HiL simulation CSV log into a dictionary of numpy arrays."""
    data = {}
    
    with open(filepath, 'r') as f:
        reader = csv.DictReader(f)
        columns = reader.fieldnames
        
        # Initialize lists for each column
        for col in columns:
            data[col] = []
        
        for row in reader:
            for col in columns:
                try:
                    data[col].append(float(row[col]))
                except ValueError:
                    data[col].append(0.0)
    
    # Convert to numpy arrays
    for col in data:
        data[col] = np.array(data[col])
    
    return data


def plot_step_response(data, output_path="step_response.png"):
    """
    Create a 3-subplot figure showing step response for roll, pitch, and yaw.
    Each subplot shows: setpoint (dashed), actual angle (solid), and PID output.
    """
    
    cycles = data['cycle']
    
    # Detect setpoints from initial error + initial angle
    # At cycle 0, error = setpoint - angle. If angle starts at 0, error ≈ setpoint.
    roll_setpoint  = data['roll_error'][0]  + data['roll_angle'][0]
    pitch_setpoint = data['pitch_error'][0] + data['pitch_angle'][0]
    yaw_setpoint   = data['yaw_error'][0]   + data['yaw_angle'][0]
    
    # ---- Figure setup ----
    fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
    fig.suptitle('HiL Flight Controller — Step Response',
                 fontsize=16, fontweight='bold', y=0.98)
    
    # Color palette
    colors = {
        'setpoint': '#E74C3C',
        'angle':    '#2ECC71',
        'pid':      '#3498DB',
        'error':    '#F39C12',
        'grid':     '#ECF0F1'
    }
    
    # Background style
    fig.patch.set_facecolor('#1A1A2E')
    
    # ---- Subplot configuration ----
    axes_config = [
        {
            'title': 'Roll Response',
            'setpoint': roll_setpoint,
            'angle': data['roll_angle'],
            'pid': data['roll_pid'],
            'error': data['roll_error'],
        },
        {
            'title': 'Pitch Response',
            'setpoint': pitch_setpoint,
            'angle': data['pitch_angle'],
            'pid': data['pitch_pid'],
            'error': data['pitch_error'],
        },
        {
            'title': 'Yaw Response',
            'setpoint': yaw_setpoint,
            'angle': data['yaw_angle'],
            'pid': data['yaw_pid'],
            'error': data['yaw_error'],
        },
    ]
    
    for ax, config in zip(axes, axes_config):
        # Dark theme for subplot
        ax.set_facecolor('#16213E')
        ax.tick_params(colors='#CCCCCC', labelsize=9)
        for spine in ax.spines.values():
            spine.set_color('#333366')
        
        # Setpoint reference line
        ax.axhline(y=config['setpoint'], color=colors['setpoint'],
                    linestyle='--', linewidth=1.5, alpha=0.8, label='Setpoint')
        
        # Actual angle
        ax.plot(cycles, config['angle'], color=colors['angle'],
                linewidth=1.8, label='Actual Angle (°)', zorder=3)
        
        # PID output (secondary y-axis)
        ax2 = ax.twinx()
        ax2.plot(cycles, config['pid'], color=colors['pid'],
                 linewidth=1.0, alpha=0.6, label='PID Output (Q8.8)')
        ax2.set_ylabel('PID Output', color=colors['pid'], fontsize=9)
        ax2.tick_params(axis='y', colors=colors['pid'], labelsize=8)
        for spine in ax2.spines.values():
            spine.set_color('#333366')
        
        # Error trace
        ax.plot(cycles, config['error'], color=colors['error'],
                linewidth=1.0, alpha=0.4, label='Error (°)')
        
        # Labels and legend
        ax.set_ylabel('Angle (°)', color='#CCCCCC', fontsize=10)
        ax.set_title(config['title'], color='#FFFFFF', fontsize=12,
                     fontweight='bold', pad=8)
        ax.grid(True, color=colors['grid'], alpha=0.1, linewidth=0.5)
        
        # Combined legend
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2,
                  loc='upper right', fontsize=8,
                  facecolor='#1A1A2E', edgecolor='#333366',
                  labelcolor='#CCCCCC')
    
    # X-axis label
    axes[-1].set_xlabel('Simulation Cycle', color='#CCCCCC', fontsize=11)
    
    # ---- Motor duty subplot (bonus info at bottom) ----
    # We'll add it as annotation text instead to keep 3 subplots
    
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(output_path, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor(), edgecolor='none')
    plt.close()
    
    print(f"Plot saved to: {output_path}")
    
    # Print summary statistics
    print("\n=== Step Response Summary ===")
    for config in axes_config:
        final_angle = config['angle'][-1]
        final_error = abs(config['error'][-1])
        print(f"  {config['title']:20s} | Setpoint: {config['setpoint']:+8.3f}° | "
              f"Final: {final_angle:+8.3f}° | Error: {final_error:.3f}°")


def main():
    parser = argparse.ArgumentParser(
        description='Plot step response from HiL flight controller simulation')
    parser.add_argument('--csv', type=str, default='hil_flight_log.csv',
                        help='Path to the simulation CSV log')
    parser.add_argument('--output', type=str, default='step_response.png',
                        help='Output plot image path')
    args = parser.parse_args()
    
    if not os.path.exists(args.csv):
        print(f"Error: CSV file not found: {args.csv}")
        print("Run the cocotb simulation first: cd sim && make")
        sys.exit(1)
    
    data = load_csv(args.csv)
    plot_step_response(data, output_path=args.output)


if __name__ == '__main__':
    main()
